/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;





import java.beans.PropertyVetoException;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelo.ConexionBD;


/**
 *
 * @author DARSY
 */
public class MDInicio extends javax.swing.JFrame {
        
    FRMregistroUsuarios fRMregistroUsuarios;
    FRMregistrObjeto fRMregistrObjeto;
    FRMregistrarProveedor fRMregistrarProveedor;
    FRMbuscarObjeto fRMbuscarObjeto;
    FRMbuscarProveedor fRMbuscarProveedor;
    FRMprestarObjeto fRMprestarObjeto;
     
    //AQUI AGREGAMOS FORMULARIOS CREADOS
      
    
    
    
    
    
    public MDInicio() {
       ConexionBD Con = new ConexionBD();
       Con.ConexionBD();  //CONEXION A LA BASE DE DATOS
       initComponents();
       
       fRMregistroUsuarios = new FRMregistroUsuarios();  //INSTACIAMOS FORMULARIOS
       fRMregistrObjeto = new FRMregistrObjeto();
       fRMregistrarProveedor = new FRMregistrarProveedor();
       fRMbuscarObjeto = new FRMbuscarObjeto();
       fRMbuscarProveedor = new FRMbuscarProveedor();
       fRMprestarObjeto = new FRMprestarObjeto();
       
       escritorio.add(fRMregistroUsuarios);
       escritorio.add(fRMregistrObjeto);
       escritorio.add(fRMregistrarProveedor);
       escritorio.add(fRMbuscarObjeto);
       escritorio.add(fRMbuscarProveedor);
       escritorio.add(fRMprestarObjeto);
       
       //AÑADIMOS AL ESCRITORIO LOS MISMOS
       
       setIconImage(new ImageIcon(getClass().getResource("../imagenes/logoSena.png")).getImage());
       setExtendedState(JFrame.MAXIMIZED_BOTH);
       this.setLocationRelativeTo(null);
       ingreso. setIconImage(new ImageIcon(getClass().getResource("../imagenes/logoSena.png")).getImage());
       ingreso.setSize(460,450);
       ingreso.setLocationRelativeTo(this);
       ingreso.setTitle("SISTEMA ALMACÉN");
       ingreso.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ingreso = new javax.swing.JDialog();
        btIngresa = new javax.swing.JButton();
        usu = new javax.swing.JTextField();
        laUsuario = new javax.swing.JLabel();
        laContraseña = new javax.swing.JLabel();
        contra = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        salir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        escritorio = new javax.swing.JDesktopPane();
        fondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        btRegistrar = new javax.swing.JMenu();
        btnRegisUsu = new javax.swing.JMenuItem();
        btRegObj = new javax.swing.JMenuItem();
        btRegProvee = new javax.swing.JMenuItem();
        btBuscar = new javax.swing.JMenu();
        btnBuscarObj = new javax.swing.JMenuItem();
        btBuscarprovee = new javax.swing.JMenuItem();
        btPrestar = new javax.swing.JMenu();
        btnPrestarObj = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        btnSalirApp = new javax.swing.JMenuItem();

        ingreso.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        ingreso.setBackground(new java.awt.Color(255, 255, 255));
        ingreso.setForeground(new java.awt.Color(255, 255, 255));
        ingreso.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btIngresa.setBackground(new java.awt.Color(255, 153, 0));
        btIngresa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btIngresa.setText("INGRESAR");
        btIngresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIngresaActionPerformed(evt);
            }
        });
        ingreso.getContentPane().add(btIngresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, -1, -1));

        usu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 0)));
        ingreso.getContentPane().add(usu, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 210, 30));

        laUsuario.setBackground(new java.awt.Color(0, 0, 0));
        laUsuario.setFont(new java.awt.Font("Rockwell Nova Extra Bold", 1, 12)); // NOI18N
        laUsuario.setForeground(new java.awt.Color(255, 255, 255));
        laUsuario.setText("USUARIO:");
        laUsuario.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        ingreso.getContentPane().add(laUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 206, -1, 20));

        laContraseña.setFont(new java.awt.Font("Rockwell Nova Extra Bold", 1, 12)); // NOI18N
        laContraseña.setForeground(new java.awt.Color(255, 255, 255));
        laContraseña.setText("CONTRASEÑA:");
        ingreso.getContentPane().add(laContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        contra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 0)));
        ingreso.getContentPane().add(contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 210, 30));

        jPanel1.setBackground(new java.awt.Color(255, 51, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("INICIO DE SESIÓN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 11, -1, -1));

        salir.setBackground(new java.awt.Color(255, 153, 0));
        salir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/16Salir.png"))); // NOI18N
        salir.setText("salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jPanel1.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, -1, -1));

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoSena.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 450, 360));

        ingreso.getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 410));

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu1.setText("File");
        jMenuBar3.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar3.add(jMenu2);

        jMenu6.setText("File");
        jMenuBar4.add(jMenu6);

        jMenu7.setText("Edit");
        jMenuBar4.add(jMenu7);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("principal");

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N

        escritorio.setLayer(fondo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escritorioLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(fondo)
                .addContainerGap())
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/72NotaPluma.png"))); // NOI18N

        btnRegisUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuarios.png"))); // NOI18N
        btnRegisUsu.setText("Registrar Usuario");
        btnRegisUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisUsuActionPerformed(evt);
            }
        });
        btRegistrar.add(btnRegisUsu);

        btRegObj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/24RegistroProd.png"))); // NOI18N
        btRegObj.setText("Registrar Objeto");
        btRegObj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegObjActionPerformed(evt);
            }
        });
        btRegistrar.add(btRegObj);

        btRegProvee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/24RegistroProvee.png"))); // NOI18N
        btRegProvee.setText("Registrar Proveedor");
        btRegProvee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegProveeActionPerformed(evt);
            }
        });
        btRegistrar.add(btRegProvee);

        jMenuBar1.add(btRegistrar);

        btBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/72Lupa.png"))); // NOI18N

        btnBuscarObj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/24li.png"))); // NOI18N
        btnBuscarObj.setText("Buscar Objeto");
        btnBuscarObj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarObjActionPerformed(evt);
            }
        });
        btBuscar.add(btnBuscarObj);

        btBuscarprovee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/24BuscarUsu.png"))); // NOI18N
        btBuscarprovee.setText("Buscar Proveedor");
        btBuscarprovee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarproveeActionPerformed(evt);
            }
        });
        btBuscar.add(btBuscarprovee);

        jMenuBar1.add(btBuscar);

        btPrestar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/72Carro.png"))); // NOI18N

        btnPrestarObj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/24tiempo.png"))); // NOI18N
        btnPrestarObj.setText("Prestar Objeto");
        btnPrestarObj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrestarObjActionPerformed(evt);
            }
        });
        btPrestar.add(btnPrestarObj);

        jMenuBar1.add(btPrestar);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/72Stop.png"))); // NOI18N

        btnSalirApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/24Salir+.png"))); // NOI18N
        btnSalirApp.setText("Salir");
        btnSalirApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirAppActionPerformed(evt);
            }
        });
        jMenu5.add(btnSalirApp);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btRegObjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegObjActionPerformed
     
        FRMregistrObjeto llamar = new FRMregistrObjeto();
        escritorio.add(llamar);
        llamar.show();
        
        
    }//GEN-LAST:event_btRegObjActionPerformed

    private void btnSalirAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirAppActionPerformed
        ConexionBD Con = new ConexionBD();
        Con.desconectarBD();
        try {
            fRMregistroUsuarios.setClosed(true);
            fRMregistrObjeto.setClosed(true);
            fRMregistrarProveedor.setClosed(true);
            fRMbuscarObjeto.setClosed(true);
            fRMbuscarProveedor.setClosed(true);
            fRMprestarObjeto.setClosed(true);
                       
        } catch (PropertyVetoException ex) {
            System.err.println("ERROR AL SALIR:"+ex.getMessage());
        } 
        
        System.exit(0);    
        
    }//GEN-LAST:event_btnSalirAppActionPerformed

    private void btIngresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIngresaActionPerformed
        
        try {
            ConexionBD Con = new ConexionBD();
            String u = usu.getText();
            String p = contra.getText();
            Con.ConexionBD();
            
            String SQL = "SELECT nick, password FROM usuarios "
                    + "WHERE nick ='"+u+"' AND password = '"+p+"'"; 
            Con.resultado = Con.sentencia.executeQuery(SQL);
            
            if(Con.resultado.next()){
                setVisible(false);
                MDInicio inicio = new MDInicio();
                inicio.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrectos");
            }
            
        } catch (Exception e) {
        }
              
    }//GEN-LAST:event_btIngresaActionPerformed

    private void btBuscarproveeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarproveeActionPerformed
        
        FRMbuscarProveedor mesa = new FRMbuscarProveedor();
        escritorio.add(mesa);
        mesa.show();
        
        
        
        
    }//GEN-LAST:event_btBuscarproveeActionPerformed

    private void btnPrestarObjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestarObjActionPerformed
        
       FRMprestarObjeto pres = new FRMprestarObjeto();
       escritorio.add(pres);
       pres.show();
              
               
        
        
    }//GEN-LAST:event_btnPrestarObjActionPerformed

    private void btnBuscarObjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarObjActionPerformed
        
        FRMbuscarObjeto bus = new FRMbuscarObjeto();
        escritorio.add(bus);
        bus.show();
        
        
        
    }//GEN-LAST:event_btnBuscarObjActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);       
    }//GEN-LAST:event_salirActionPerformed

    private void btRegProveeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegProveeActionPerformed
    
        FRMregistrarProveedor lola = new FRMregistrarProveedor();
        escritorio.add(lola);
        lola.show();
        
        
        
    }//GEN-LAST:event_btRegProveeActionPerformed

    private void btnRegisUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisUsuActionPerformed
       
        
         FRMregistroUsuarios ruta = new FRMregistroUsuarios();
         escritorio.add(ruta);
         ruta.show();
         
    }//GEN-LAST:event_btnRegisUsuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDInicio().setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu btBuscar;
    private javax.swing.JMenuItem btBuscarprovee;
    private javax.swing.JButton btIngresa;
    private javax.swing.JMenu btPrestar;
    private javax.swing.JMenuItem btRegObj;
    private javax.swing.JMenuItem btRegProvee;
    private javax.swing.JMenu btRegistrar;
    private javax.swing.JMenuItem btnBuscarObj;
    private javax.swing.JMenuItem btnPrestarObj;
    private javax.swing.JMenuItem btnRegisUsu;
    private javax.swing.JMenuItem btnSalirApp;
    private javax.swing.JPasswordField contra;
    public static javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel fondo;
    private javax.swing.JDialog ingreso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel laContraseña;
    private javax.swing.JLabel laUsuario;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private javax.swing.JButton salir;
    private javax.swing.JTextField usu;
    // End of variables declaration//GEN-END:variables
}
